version: 2
updates:
  - package-ecosystem: github-actions
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: /
    schedule:
      interval: monthly

  # check submodule labs are up-to-date
  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: daily
